a = input("Digite algo: ")
print("O tipo primitivo desse valor eh", type(a))
print("Só te espaços? {}".format(a.isspace()))
print("É um número? {}".format(a.isnumeric()))
print("É alfabético? {}".format(a.isalpha()))
print("É alfanumérico? {}".format(a.isalnum()))
print("Está em maiúsculas? {}".format(a.isupper()))
print("Está em minúsculas? {}".format(a.islower()))
print("Está capitalizada? {}".format(a.istitle()))
